---
project_name: gpbackup_exporter

builds:
  - env: 
      - CGO_ENABLED=1
    goos: 
      - linux
    goarch:
      - amd64
    flags: 
      - -trimpath
      - -mod=vendor
    ldflags: "-s -w -X main.version={{ .Version }}"
    main: .

archives:
  - id: gpbackup_exporter
    files:
      - LICENSE
    format: tar.gz
    name_template: '{{ .Binary }}-{{ .Version }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    wrap_in_directory: true

nfpms:
  - id: gpbackup_exporter
    package_name: gpbackup_exporter
    builds:
      - gpbackup_exporter
    homepage: https://github.com/woblerr/gpbackup_exporter
    maintainer: Anton Kurochkin
    description: Prometheus exporter for gpbackup
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    file_name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    contents:
      - src: gpbackup_exporter.service.template
        dst: /etc/systemd/system/gpbackup_exporter.service
        type: config

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: true

changelog:
  skip: true