tls_server_config:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIC9jCCAd4CCQCeGU78fxVdJjANBgkqhkiG9w0BAQsFADA8MRwwGgYDVQQKDBNw
    Z2JhY2tyZXN0X2V4cG9ydGVyMRwwGgYDVQQLDBNwZ2JhY2tyZXN0X2V4cG9ydGVy
    MCAXDTIxMTIwOTE4MjIwN1oYDzIxMjExMTE1MTgyMjA3WjA8MRwwGgYDVQQKDBNw
    Z2JhY2tyZXN0X2V4cG9ydGVyMRwwGgYDVQQLDBNwZ2JhY2tyZXN0X2V4cG9ydGVy
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2MuYk65TziOvh5Y/UohC
    yBQYkSijTIM2R5qcZsG6kociqLJbnLpxa645hXcJec9cP+P8FMhEWNHLfOuPuwEm
    tLdhW2SVezwKrLnCWxAwF6dSwslsV4Aq91WjaUafz4JTyMsHFUcgC9iw1jwaw96z
    yIY+bjm4xQzF3Rm5soNquCyzdlDlkYO/W56oDU5QoTvh3uV/vOD4qU5FaGS1eUjq
    B43eh4ORmK+VY+l86BIMlIPXDcxfh9SvUq5om3juqPuzjGZ9xgcm/H+J6anT7PV9
    qq/lPgS099GR7OLox+RCw5ILQgh5IuHiLLmCJs5IghNRejJIwrBae8wVXYx8grqU
    cwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQDF7e9TWhCvhEwAUyMkGs2E2w3CxiRu
    kqBgJR0OK1MHZk8bsfp7RSK6+tq2IyzsNCUlK7mdf9Y/vtXCvePfC2e6pfSu0L7v
    NwEHocrxaNEKh+qQokVxYNxXYKFP7JiVq2XErBgAsABYu//jlsCjVg3HkuFxCfyY
    dx8k1Xz3ULjgtuOoAsR6oypnumYGlrRb0ShUFulAcYlq1kA+ZzrFMuFp5TMWmzd5
    3YYp6V3PAMY2sRxqfSg5Kw37w7c983FKH10B4hIt9dfOdSXsN1JqnP54TUcR0Rgy
    +m58+G1az06pQ0ajREJwzZrlEmZDkMUmxgPnP8ekz+b7t6c2MZExr87r
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDYy5iTrlPOI6+H
    lj9SiELIFBiRKKNMgzZHmpxmwbqShyKoslucunFrrjmFdwl5z1w/4/wUyERY0ct8
    64+7ASa0t2FbZJV7PAqsucJbEDAXp1LCyWxXgCr3VaNpRp/PglPIywcVRyAL2LDW
    PBrD3rPIhj5uObjFDMXdGbmyg2q4LLN2UOWRg79bnqgNTlChO+He5X+84PipTkVo
    ZLV5SOoHjd6Hg5GYr5Vj6XzoEgyUg9cNzF+H1K9SrmibeO6o+7OMZn3GByb8f4np
    qdPs9X2qr+U+BLT30ZHs4ujH5ELDkgtCCHki4eIsuYImzkiCE1F6MkjCsFp7zBVd
    jHyCupRzAgMBAAECggEBALJhMzWwZrximHcTpR6fh3NhNaWarmKyQ+M+0BmspXsT
    Pe1YdBDNR622ORYcD+vuNpVLXYssDTCXzrsGh8jy9YoUqUKtzGEN0iq03bpX43pS
    7sHfQgntJ21DRaXFupDfR1kb1MQpNbEJptdftRYdFAiWjJ/dVq6sB9IY7LZ5c0H9
    4WfR9k06RuRaRUTVbGEgxSgiI4pN+BysHbBlLvemTcH0OcqAAVy7tu6KffLJlA9D
    +RBIpaANMXeivSc6UOS9MYAYsKH8FT09TbVdCFPwWuK5UZoWoiEgG86X5rKFrnwP
    Fujwr0AMlW7McDy2BQ0XbqrBeF3jdv5bsY/5T4E9w2ECgYEA+usHj/BMnhEVbf6W
    VQzBXtTxPlFFvD5OTCWnDc3fy0vLXcKhL3LDotsz6BkrDDuvlo6zEPnuKvq6zNB3
    QnPYv7pjK0dfrxt+V0PFs07H8GbPY6aGl9FDl8se/KHZoNHYqi405JmbPUnyf50b
    zpKRZyrvWEjqOIWVMl0B8tylNncCgYEA3S+lLXOPt2Rk/Jxx56+Ijas3yNCRQURM
    PnnHP25kBi21HdHiO2y1yldUUFNIHr7XcM4WfMC90Joq6/okNt/wWm88uYBIrOkt
    WpbzxFLJHvVaiExF+rRXCRU7x3yrsseisQFBqZx+iu4MYkJrDDelotJxDOzfCv6d
    NBvQ0i1hBOUCgYB5POrQf7llfreuCB83RQyB974A8GATjr9iR6cqIlmJ7zt6ODqN
    pJQmsmeoM9D6/jPfOWAISdrsZW2w3OFi+Hq4WSTlmnz/LPekzphOBTjSTbrTWXkb
    Df/s7jYwtztiW0KnJ+BivF2oBXzocE8pRuR+xt4S+FhDqzflt87jO/2QDQKBgDry
    ibj1RWYA0ZEpOIogk+n9qZ5RR4T3aMJ1vg4/o1SqNcy+tOZVcJV+dK/7ogrfnZco
    tYGF9JB1pd7CCYi+YdYYMzzU3YmHk1jDRjAaSBOCHCCbA0NvcIqxJ/9gUHoTDl7S
    EOfdFzR7gL1nKhRVeEVOhGaHcmIBvW+3wg1hnqupAoGBAKpdOSmBlOSykw7AQP1m
    Bm6qgecfg8xDkIpnvH22opg1LrG33GfS5lpjyHJMoWUdLcmzZYgrJeygxFBvBzvf
    5sWiDvc9InPyWlZ4IPdfsTlbaJIrf4z55/1jfKzzCFnSyHjbf4aqlHMLmrBmLQwH
    CXIM8oJcMAwnQfVgaX3/Def2
    -----END PRIVATE KEY-----
  client_auth_type: "VerifyClientCertIfGiven"
