tls_server_config:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIDUzCCAjugAwIBAgIUAsCpzItrY8CD+W04JwgpGh85nHIwDQYJKoZIhvcNAQEL
    BQAwODEaMBgGA1UECgwRZ3BiYWNrdXBfZXhwb3J0ZXIxGjAYBgNVBAsMEWdwYmFj
    a3VwX2V4cG9ydGVyMCAXDTI0MTIxMjE2NDM0NVoYDzIxMjQxMTE4MTY0MzQ1WjA4
    MRowGAYDVQQKDBFncGJhY2t1cF9leHBvcnRlcjEaMBgGA1UECwwRZ3BiYWNrdXBf
    ZXhwb3J0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCsfbChEvM8
    kkgbJKjWfPBjiXRUfW7+c9jm/nHSZ/UoY4zn6w7+q2kSzLbHDcUIwVZNZZkW+j4o
    pSYnYwf0GCX/7Sh1I5/JC27/WLPOZtwqv05t9pHBhKRxHQoK3+03Ye+V72SmiX01
    54pI/Z8cbzgb8zX1H8cJDfZs3uyqj/eAqRluY6mxzk4pA+D6upMl4R4eOMj68Xkp
    aqVIuMIDctGWtjdBE/3yEWTSCh8KhwrMgvpS2dNW3FGegZxzrMDhZAnO+bfbOshV
    qzPPUpihrxDcIHboOo6bY66xp2V3w9dACE8R8oObNHhHV8ru8fleJXcMGmzHzEN9
    6BjsKszya5jVAgMBAAGjUzBRMB0GA1UdDgQWBBS+dcPTxuoHm0ixVHBI5l51X0+c
    uDAfBgNVHSMEGDAWgBS+dcPTxuoHm0ixVHBI5l51X0+cuDAPBgNVHRMBAf8EBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBIIVDM/0ZzykOy5et3fsJu/yhEOQ/S5RyC
    wFzqLCDR+AsGhbqT3lfMU15ArCq3Kzi7XvOQEW/YKduuBDgP2S0GmGKmwFsTDBwV
    KaeZKk2pXOaxXSqXvB8Lj1VedD9B+lSTiu24lVfe0INkDw9N6KHiFjvm0El9HMO7
    JpvLl3VDDraR8S5wNPg6SUpI7smdue7q8ev9sSHwvtdaf+KMDrFmpIq+EgLdL1Lh
    Je4dFvDJ0szReyz9QA1nXuSGMq3BCV8yH2KLUXF4/FFqL0bJqqf+Vb4rdPwasmEG
    AnDurQnhQ2yPOHjyHWlZ2vZlv1BQmjHrlpcSmcOFHBvYiEslKftA
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCsfbChEvM8kkgb
    JKjWfPBjiXRUfW7+c9jm/nHSZ/UoY4zn6w7+q2kSzLbHDcUIwVZNZZkW+j4opSYn
    Ywf0GCX/7Sh1I5/JC27/WLPOZtwqv05t9pHBhKRxHQoK3+03Ye+V72SmiX0154pI
    /Z8cbzgb8zX1H8cJDfZs3uyqj/eAqRluY6mxzk4pA+D6upMl4R4eOMj68XkpaqVI
    uMIDctGWtjdBE/3yEWTSCh8KhwrMgvpS2dNW3FGegZxzrMDhZAnO+bfbOshVqzPP
    UpihrxDcIHboOo6bY66xp2V3w9dACE8R8oObNHhHV8ru8fleJXcMGmzHzEN96Bjs
    Kszya5jVAgMBAAECggEAFF69irAduIP/7vCr3bSggOi9K7MqdfNBZLocv//V5GCp
    RcQtH6cnf/hcB3LZV3jZk8dRRnTj/VHPiSw5RrrJVglwUzETUB9BCvezOEdObd/s
    x7CsMuHSt6b5xiH+tiEjNZ4xUTeAaWrAGnGVJjr+MdLNhvarPyb+eIn1AgmBbZiY
    wSj5xQUBvI6XdGsy2/Wqt2yaHHzJ0xAVsvWoVXqFzsEok7Jt0MTunBVLDYAjCjjl
    QqrKZZOnVJVy0NvP7gB44gXQfXs7WqjvQhYn2VNfMqHTPNk18SQehEyQ2HPwrMKl
    tOq1x0ZTbFJBpVmjAGmkP+h1GB/Nq9m5eTLLghf2oQKBgQDqhmzV5CPmt6PsYapw
    FlF5ill6KPcL1SftfPJrpAr2TdSBvGFf5mTXA6COmIhLQD0CnxZ54p/Weaf2DrRt
    Ap11C00xqfuF0G5CKNJ3rcHrHZgxZWzT9QNNnJsjSvQCDuNCDxgMSmjIt2jIKdD/
    GUMLrBL4u685aN+/oA3MsJBGsQKBgQC8SRqaP9rnM3GVzHWw351yXRYMnQ7ocmnS
    q24cc0G1kVJTVXal8ch1XKFk0s4wk7OE+Oi1NtfyQ18A5lBNl3s4BDNlQR3j+SWp
    D+MMP0kAbuYEKVT0gbEl8XAMF+oKyWeFMc8dOw+A9+ORNoH26P3Z+7MS2P8HWSRJ
    yWZ9zhJFZQKBgBn7zMEh5qxgOkQtSfHjNyGtJ162fTCNbEAOsNkmMqS5WMsK8Qrr
    /s4ns7k4wxj7RAcvUxEr/6OGlQpY9LqDKKjYGLRg7eIUhrLDzRW/ZZXEEKGgaB9P
    rQ8DQ9j0K/ayaZFfFL3/3H4oe+55W5N33ArGBNAUE0TcDrYvaHf+M+3xAoGBALXW
    sD96HfIdx7vRO3R3cbpqVgoWgLhTDwprj6sgULyGvYhHyI+ZQ2y86g3SXVmiu8RX
    E383mTSahhz7UWCuRE0kGXLXgYOTMiDle/RvBhTKBZDNTgPZYPlxBDJZwilqu3Ry
    V0E2sdFvFjM+/iM0fz1PjXFNandxSs+MF1S2eQTVAoGBALJkhp9xpKuCP9uty3Dn
    1lF9hmp+qsNeFF62Ce31/JiJHPF5Vjf+YkDumTuanjLXyHuZT22cr988tMkUWkY9
    54Rv1f8fUutvjPRn7dJU+llQx4QGZH5Aw8QXwPv0K0S/8DedFiNg44ARZsusIsUA
    jTrlgYJ/mOowZrNYo/CRw9tU
    -----END PRIVATE KEY-----
  client_auth_type: "VerifyClientCertIfGiven"
